### ISSUE TITLE
Attempting to compile

### ISSUE THREAD

**Issue by dreamGal** [milostosic/MTuner#13]
Apologies if this is a very naive question but when I try to build the solution from command line I switch to the current directory and get a: _'genie' is not recognized as an internal or external command, operable program or batch file._ error

Looks like the only 2 files in that folder are genie.lua and MTuner.lua

Is there something I'm missing?

thanks

**Comment by milostosic** [comment]
I need to put up more detailed instructions :)
GENie binary is located in 'build' project:
~/build/tools/OS/genie
