### ISSUE TITLE
Filtering crashes

### ISSUE THREAD

**Issue by kikijiki** [milostosic/MTuner#14]
Disabling and reenabling filtering always makes mtuner crash.

**Comment by milostosic** [comment]
Can you provide more information? Are you using 3.6.8 or you have built it yourself?

**Comment by kikijiki** [comment]
I'm using 3.6.8, I downloaded the zip release (running on win7).

**Comment by milostosic** [comment]
Can you try with the new build? I was unable to reproduce this even a single time.

**Comment by kikijiki** [comment]
Thanks for the follow-up.
I tried the new build but I seem to a different problem now.
- After dropping an exe on MTuner profiling ends immediately with this message: `Capture file was only partially loaded! Information may be missing from the profile!`. Only a few milliseconds of data get recorded.
- Tried opening an file saved with the older version: the same message as above comes out, and in the end most of the data is not loaded.

Smaller bugs:
- The little arrow that you click to expand the call stack tree is not visible.
- The "Welcome to MTuner, set your PDB symbol servers" popup is shown every time even if symbols are already saved.

Don't know if it makes a difference but I'm using the zip version since the installer triggers my AV.

**Comment by milostosic** [comment]
Starting with smaller ones: 

- I added a check box to switch off welcome dialog
- Fixed a Qt style sheet issue that affected visibility of some elements

I'll check what's happening with the broken capturing...
ZIP and MSI are identical in content, no clue why some AVs nag about it.

**Comment by milostosic** [comment]
New build is up, everything should be fine now.

**Comment by kikijiki** [comment]
Thanks, I'll give it a try later.
