### ISSUE TITLE
Project disappears after clicking Run

### ISSUE THREAD

**Issue by Zbyl** [milostosic/MTuner#16]
1. In Settings > Manage projects I chose executable and click Add.
The executable appears on the list.
2. Then I click Run - sometimes MTuner crashes here (I had it the first few times, but I cannot reproduce any more).
3. After Run I go to Settings > Manage projects again, and the list is empty.

When in Settings > Manage projects I don't click Run, but OK, and then go to Settings > Manage projects again and click Run the project does not disappear any more.

In case of crashes I mentioned in point 2: after starting MTuner again the list of projects is empty (every time I had 2 projects before crash).

**Comment by milostosic** [comment]
Thanks for the report, I'll check this carefully before next release.

**Comment by milostosic** [comment]
Question: after adding a project, have you pressed 'OK'?
If not, added projects will not be saved - same behavior for pressing 'Cancel' or escape key.

**Comment by Zbyl** [comment]
No, I didn't press OK.
I assumed that Run means "Save and Run", not "Cancel, but Run".
I also assumed that "Add" button means "Add and Save".

But if that's expected behaviour, I guess you can close this issue.

**Comment by milostosic** [comment]
Ok, I added a message box to warn users in case of a modified list that it won't be saved.
