### ISSUE TITLE
PS4 captures do not have any module info and cause the GUI to assert when loaded

### ISSUE THREAD

**Issue by EBatut-ALG** [milostosic/MTuner#18]
Hi

I am integrating the rmem files in my PS4 project, calling rmemInit, rmemAllocAligned, rmemFree and rmemShutDown in my runtime, and getting seemingly correct capture files.

When I try to load these capture files in the MTuner GUI, the parsing of the capture completes successfully and the `rtm::Capture::LoadResult res = ctx->m_capture->loadBin(fn.c_str());` statement in mtuner.cpp at line 790 returns with `rtm::Capture::LoadSuccess`.

A few lines later, during the toolchain setup (`setupLoaderToolchain(ctx, _file, m_gccSetup, m_fileDialog, this, symStore);` at line 801), the ELF file is located, and the toolchain checked (the PS4 toolchain is correctly found on my machine). At the end of the function, line 130, `_context->setToolchain(tc);` is called. In `CaptureContext::setToolchain()`, the toolchain is a GCC variant, so nothing special is done in the `switch` statement. Then, line 67 in capturecontext.cpp, symbol resolver creation is attempted (`m_symbolResolver = rdebug::symbolResolverCreate( m_capture->getModuleInfos().data(), (uint32_t)m_capture->getModuleInfos().size(), &_tc);`). As my capture has no module info whatsoever, `m_capture->m_moduleInfos` is emtpy, the first assert at the beginning of `rdebug::symbolResolverCreate()` fires, because `_moduleInfos` is `NULL`.

I looked at the capture parsing code (capture.cpp), and as far as I can tell, module info is either added (via `addModule`) when symbols are loaded early in the capture parsing code (`if (!loadSymbolInfo(loader, fileSize))`, line 324 in capture.cpp), or when `rmem::LogMarkers::Module` markers are found when parsing the capture. First case does not happen with my capture because `symbolInfoSize` is 0 (`getSymbolInfo()` is only implemented for Windows and X360 platforms), and second case does not happen either because I am not calling `rmemAddModuleC|W()` in my runtime.

So my question is: what am I missing :) Should I try to get the module's name/base/size from the PS4 runtime and manually add it to the capture, or should there be some kind of "this is a platform where it is likely module info will be absent, module info should be directly populated with the EXE/ELF name by default" bypass (in which case base address and size are still missing I guess)?

Thanks for your help!

**Comment by milostosic** [comment]
Thanks for a very detailed report, I'll look into this asap.

**Comment by milostosic** [comment]
Debugged this and fixed most of the issues, there's one problem left I have to be careful with as it affects all gcc/clang toolchains. To be specific: there's a problem with paths and quotes when launching addr2line and related processes (all in rdebug). I'll probably fix this by tomorrow evening.

**Comment by EBatut-ALG** [comment]
Many thanks Milos, I'll watch this issue and pull again in a day or two to get the fix. 

Thanks again for your invaluable help and tool!

**Comment by milostosic** [comment]
New build is up (v4.0.3), I tested it with MinGW (gcc) and PS4 (clang) - worked fine.

**Comment by EBatut-ALG** [comment]
Thanks a lot !
