### ISSUE TITLE
Question about the stars on this repository

### ISSUE THREAD

**Issue by vinniefalco** [milostosic/MTuner#2]
I just noticed that this repository appeared on "GitHub C++ Trending". I am looking at the star history:
http://www.timqian.com/star-history/#milostosic/MTuner

It looks like the repository debuted on August 23 with 150 stars, then got another 200 on August 24, and then on August 25th it received over 250 stars.

I'm wondering, how is this possible? Is MTuner being promoted elsewhere? How did so many people find out about this repository and give it a star in just 3 days? I would like to promote my own Boost C++ library, called Beast, which implements HTTP and WebSocket:
https://github.com/boostorg/beast

By the way your application looks beautiful, I am trying it out now - very helpful!

Thanks

**Comment by clementperon** [comment]
Top of HN : https://news.ycombinator.com/

**Comment by vinniefalco** [comment]
Thanks!!
