### ISSUE TITLE
Symbols don't seem to apply

### ISSUE THREAD

**Issue by asafshakedverint** [milostosic/MTuner#24]
Using latest release v4.0.7 on Win7 x64 (tried more than one PC)

I'm setting local store with path to output files from my build server

Opening previously recorded or recording new session

Call stack window is empty... Symbols don't seem to apply :/

What am I doing wrong ?

**Comment by milostosic** [comment]
Hard to say. Best would be to debug it locally...
I'd appreciate if you find what the cause is and report it back. Will leave the issue open for a few days

**Comment by asafshakedverint** [comment]
Tested using simple leaking test app… now I see something on call stack

My real application to test however has hundreds of PDBs… maybe that’s the issue ?

**Comment by milostosic** [comment]
I would be guessing at best without a repro case, and that's not really an engineering approach :)
If you manage to reproduce the problem on a smaller scale I'd love to look into this.

**Comment by asafshakedverint** [comment]
Thanks… I’ll do my best

**Comment by darknesswind** [comment]
The DIA interface load symbols directly but not using the search path. The search path may be using in Dbg
Help library only.

**Comment by darknesswind** [comment]
Sorry, I make a mistake, It is not the reason I fail to load the symbols.
I found that if I start a process on a remote disk, just like \\dev.test.net\release\test.exe, and the symbol file local in the same folder, call of IDiaDataSource::loadDataForExe will fail because rtm::WideToMulti convert the path to a UNC path.

**Comment by darknesswind** [comment]
the convert result just like: UNC\\\\dev.test.net\release\
and the stander UNC path should be: \\\\?\UNC\dev.test.net\release\
But even if I try "\\\\?\UNC\dev.test.net\release\", IDiaDataSource::loadDataForExe will fail.

**Comment by milostosic** [comment]
If you have time to contribute a fix it would be appreciated. I'm currently very busy with other projects.

**Comment by milostosic** [comment]
Reason was to handle very long path names, by prepending "\\?\" limit goes up substantially, if I remember correctly up to 32K characters, depending on Windows version.

**Comment by darknesswind** [comment]
But why `makeLongPath` skip the `longPathPrefix` (`\\?\`) using `return _outBuff + 4` ?

**Comment by milostosic** [comment]
Hacky convenience, you could use the buffer passed in (_outBuff) or the return value if you don't care about long paths (when you *know* it's not long).
