### ISSUE TITLE
add flamegraph visualization

### ISSUE THREAD

**Issue by milianw** [milostosic/MTuner#26]
The 2D visualization is not as easy to understand nor as usable as a flamegraph. Please consider adding such a visualization as explained here: http://www.brendangregg.com/FlameGraphs/memoryflamegraphs.html

My heaptrack tool on Linux also does that and it's super helpful.

**Comment by milostosic** [comment]
One more time: please refrain posting feature requests as issues.
I'm not really inclined to do this as what I have now works for me just fine - and I have other projects to deal with as well.

I will happily take contributions like this.
