### ISSUE TITLE
inline frames are not shown on Windows

### ISSUE THREAD

**Issue by milianw** [milostosic/MTuner#28]
when one profiles an optimized binary with MTuner, the result is hard to interpret since inline frames are not shown. Take this example:

```
void myfunc()
{
    for (int i = 0; i < 100000; ++i) {
        new char;
    }
}

int main()
{
    myfunc();
    return 0;
}
```

Put it into a file `test.cpp` then compile it with `cl.exe /O2 /Zi test.cpp` and trace it with MTuner. The result looks like this:

![inlines_missing](https://user-images.githubusercontent.com/57207/33282143-04ed8cd0-d3a8-11e7-9294-fffe7319ceb2.png)

This basically makes MTuner unusable on optimized C++ code bases on Windows

**Comment by milostosic** [comment]
This is similar to [issue 33](https://github.com/milostosic/MTuner/issues/33) in the sense that I favor **fast** stack traces much more than completely accurate ones.

Two major criteria prevent me from doing this:
 - performance as mentioned above
 - can't allocate memory while collecting traces

Using APIs that are better at stack walking on Windows break both of this conditions. Unless I'm missing one? I'd be happy to learn about it...

**Comment by milianw** [comment]
As I mentioned in #33, the criteria you mention should not be a valid concern: At trace time you don't need to find inline frames, this can and should be done offline when you analyze the trace file. Also, that data can be cached by instruction pointer address, so the performance impact should be minimal.

That said, if the point is that there exists no API for Windows to find inline call frame information for a given code address, then this can of course be closed as wont-fix. I strongly suggest you to document these usability issues (this one and #33) - users will trip over it and I at least have not found any information about this.

**Comment by milostosic** [comment]
I did not say such API doesn't exist but that such API tends to break either one or both of, for me, critical criteria. Full blown stack walker that handles a lot of difficult cases is both slow and allocates memory.

What you see in the call stack is exactly what was recorded by CaptureStackBackTrace and later resolved by rdebug. I'm not removing any stack frames from user code...

Do you have a solution for this? I'll happily take it and learn something along the way.

**Comment by milianw** [comment]
It seems to me like the Windows platform API is too limited, cf.: https://stackoverflow.com/questions/47541598/profiling-inlined-c-functions-with-visual-studio-compiler

Apparently not even the VS profilers or VTune are capable of showing inline frames, since the information is lacking from the PDB files. A Premium/Ultimate VS compiler might be able to emit the right data with `/Zo`, but so far it's still unclear. as such, I think MTuner's hands are pretty much tied and there's nothing you can really do. I wasn't aware of this serious platform limitation on Windows :-(

Just one quick note: It's not about "removing any stack frames", it's about the lack of "adding inline stack frames". After inlining, there won't be a real stack frame for the inlined function with a different instruction pointer address. Rather, the debug information can and should store that information. Then you can query the debug information for every frame you get and check whether it actually represents multiple frames and show all of them to the user. On Linux this is easy to visualize. Assume you get the following backtrace:

```
                   2369f __hypot_finite (/usr/lib/libm-2.26.so)
                    a114 hypot (/usr/lib/libm-2.26.so)
                     b88 main (/ssd/milian/projects/kdab/rnd/hotspot/build/tests/test-clients/cpp-inlining/cpp-inlining)
```

Then you call `addr2line -i` on every address (the addresses above are already offsets into the modules). Above, the interesting frame is the one pointing to main:

```
$ addr2line -f -p -i -C -e /ssd/milian/projects/kdab/rnd/hotspot/build/tests/test-clients/cpp-inlining/cpp-inlining b88
std::__complex_abs(doublecomplex ) at /usr/include/c++/7.2.0/complex:589
 (inlined by) double std::abs<double>(std::complex<double> const&) at /usr/include/c++/7.2.0/complex:597
 (inlined by) double std::_Norm_helper<true>::_S_do_it<double>(std::complex<double> const&) at /usr/include/c++/7.2.0/complex:654
 (inlined by) double std::norm<double>(std::complex<double> const&) at /usr/include/c++/7.2.0/complex:664
 (inlined by) main at /home/milian/projects/kdab/rnd/hotspot/tests/test-clients/cpp-inlining/main.cpp:39
```

I was expecting that this also would work on Windows...

**Comment by milostosic** [comment]
Yes, it's not a simple issue... I did check this a bit more (while I was fixing issue [#34)](https://github.com/milostosic/MTuner/issues/34) and found some hints that this may be possible with much more elaborate PDB parsing. This would require a significant update to [rdebug](https://github.com/milostosic/rdebug) and I'm not even certain it would work. What I saw was ability to enumerate 'inlined child symbols' or something like that - sounds like it would do the trick...

In any case, as you can see, it's more hassle than necessary, way simpler with some other toolchains :)
