### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [milostosic/MTuner#3]
I would like to point out that an identifier like “[`__RTM_MTUNER_BIGTABLE_H__`](https://github.com/milostosic/MTuner/blob/5b931a21d0401867ad1800789cc1aa552d37d09a/src/bigtable.h#L6 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by milostosic** [comment]
Cleaned up, dependencies will follow.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/milostosic/MTuner/commit/644b82d7d6eb69c855b2aa472e27f29d6c1e579d "Fix header guards").
