### ISSUE TITLE
find temporary allocations

### ISSUE THREAD

**Issue by milianw** [milostosic/MTuner#30]
In heaptrack on Linux I report temporary allocations based on a simple heuristic: Any allocation that is directly followed by its own deallocation - i.e. without any other (de)allocation happening in-between, is considered to be temporary. This, while simplistic, catches many glaring issues in applications where a simple buffer reuse can often bring tremendous performance gains. I suspect adding this metric to MTuner should be as easy as it was for heaptrack, and I know it's very useful there. I'd like to see it available on Windows and MTuner, too.

**Comment by milostosic** [comment]
It may surprise you but I am using MTuner mostly to find silly performance problems like the one you describe.

Now, your heuristic is very simple but IMO not sufficient to describe a temporary allocation. You could have a number of temporary C++ objects munching on memory within a scope and they'll all get released at the end of scope - your heuristic wouldn't consider this a temporary allocation.

A better one would be "allocated and released in the same function".
This is interesting and I may look at it at some point but I'll close this now as this is yet another feature request.

**Comment by milostosic** [comment]
It may surprise you but I actually use MTuner mostly to find silly performance issues like the one you describe.

If I get to implement something like that I wouldn't use your heuristic as I think it's way too simplistic, a better one would be "allocated and released in the same function". It seems to me that yours would miss simple things like this:
`{`
`    std::string someCppString("foo");`
`    std::string someCppString("bar");`
`}`
In any case - closing this one as it's yet another feature request.

**Comment by milianw** [comment]
How do you use MTuner to find the performance problems then - purely by looking at the number of allocations?

And for the future - are you not accepting feature requests in general, or why are you closing the requests?

**Comment by milostosic** [comment]
Number, time, etc.

I'm open to feature **suggestions** - not requests. For this I prefer to have a discussion over e-mail...
This is free software that I support in my, very limited, spare time.

**Comment by milianw** [comment]
Fair enough. What I call requests is what you mean by suggestion - I by no means intend to demand the feature now ;-) Note that I also work on multiple FOSS projects in my spare time, so I know how you feel. But I usually keep feature suggestions open as they serve multiple purposes:

- They give potential new contributors an idea on what to work on. This is really important, in my book.
- They publicly document the lack of a feature, which is helpful when googling for something.
- If the maintainer is opposed to a feature in general, that statement is also publicly documented and future interested people will be able to find it - which is not possible with private email conversations.

Anyhow, your project, your rules - I'll abide by them.

Cheers

**Comment by milostosic** [comment]
There's not many actual contributors, it's mostly people suggesting/asking for features.
I generally tend to fix bugs as soon as I can but features...

I have 20+ features for MTuner alone in my backlog, some of which are rather big, but it's rather low priority for me given that I need to distribute my time over a number of things. If a contributor comes along that's active, I'll certainly discuss some/all of these. In the mean time I think the risk of someone working on a feature that I'm working on as well is pretty much non existent :)

Your arguments are valid but we likely have different motivation here...
