### ISSUE TITLE
sorting by #allocations breaks call stack tree

### ISSUE THREAD

**Issue by milianw** [milostosic/MTuner#31]
sorting the data by number of allocations breaks the call stack tree completely, see attached screenshot:

![sort_broken](https://user-images.githubusercontent.com/57207/33282845-33291b08-d3aa-11e7-9930-7e5ea3ffee01.png)

the frame `void Worker::loadInput(void)` has 1007016 inclusive allocations, but expanding it shows only items with very few allocations. Further down a frame for `QCommandLineParser::QCommandLineParser` has one internal allocation, but expanding it shows a completely unrelated frame from the `Worker::parseFile` with 1007012 allocations - those should be part of the `loadInput` frame above.

**Comment by milostosic** [comment]
Should be fixed in v4.2.2
