### ISSUE TITLE
No Call Stack Tree since v4.0.2

### ISSUE THREAD

**Issue by pebdev** [milostosic/MTuner#37]
Used on Windows 10, I haven't information (empty window) into the 'Call Stack Tree' and 'Stack Trace' tabs.
Working with the v4.0.1 but not on all release after this.

Tested with a simple code : 
```
#include <iostream>
#include <Windows.h>

using namespace std;

int offset = 0;
char *buffer[10];

void do_allocation (void)
{
  std::cout << "alloc" << std::endl;

  buffer[offset] = (char*) malloc (50000000*sizeof(char));

  if (buffer[offset] == NULL)
  {
    offset++;
  }
}

int main()
{
  cout << "Hello World!" << endl;

  buffer[0] = (char*) malloc (10000000*sizeof(char));
  buffer[1] = (char*) malloc (30000000*sizeof(char));

  for (uint8_t i=2; i<10; i++)
  {
    do_allocation ();
    Sleep (100);
  }

  for (int i=0; i<offset;i++)
  {
    free(buffer[i]);
  }

  return 0;
}
```

Build information : 
- Visual Studio 2015 32bit
- Same settings (pdb,...) during all tests (v4.0.1, v4.0.2,...)

**Comment by milostosic** [comment]
Thanks for reporting this, just published v4.0.9. Tested with both 32 and 64bit code, seems to work fine.
