### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [milostosic/MTuner#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BinLoaderView](https://github.com/milostosic/MTuner/blob/5b931a21d0401867ad1800789cc1aa552d37d09a/src/binloaderview.cpp#L60 "Destructor for BinLoaderView")
- [OperationsList](https://github.com/milostosic/MTuner/blob/a54982db2bca5314c7bd754b09fd46b607b5f123/src/operationslist.cpp#L437 "Destructor for OperationsList")

**Comment by milostosic** [comment]
Removed, thanks!

**Comment by elfring** [comment]
* Are there [a few update candidates left over](https://github.com/milostosic/MTuner/blob/5b931a21d0401867ad1800789cc1aa552d37d09a/src/loader/binloader.cpp#L125 "Update candidate: BinLoader::loadChunk()")?
* How do you think about to use the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")" at affected source code places?
