### ISSUE TITLE
Binaries for 32 bit Windows OS

### ISSUE THREAD

**Issue by escherstair** [milostosic/MTuner#40]
In the documentation I see

> MTuner binaries can be downloaded from [releases ](https://github.com/milostosic/MTuner/releases)page

but I can find 64 bit packages only.

Would it be possible to provide binaries for 32 bit Windows OS?

Thanks in advance.

**Comment by milostosic** [comment]
Hi, sorry but since Qt no longer supports 32bit builds for Windows this is impractical.
However, it is still possible to build it yourself using an older release of Qt.
