### ISSUE TITLE
Command line parameters mixed up

### ISSUE THREAD

**Issue by djelinski** [milostosic/MTuner#42]
I'm trying to run MTuner from command line; the application expects to receive command-line parameter **-exe** or **/exe**.
Attempt 1:
>mtuner -p wfsp.exe -c "/exe"

Result:
Unrecognized argument: "\exe"
Attempt 2:
>mtuner -p wfsp.exe -c "-exe"

Result:
No arguments passed.

Adding or removing quotes does not change the outcome. This is on Windows 2012 R2.

**Comment by djelinski** [comment]
Thanks @milostosic for looking into this. I just downloaded 4.1.1 from https://github.com/milostosic/MTuner/releases/download/v4.1.1/mtuner64.zip and the command line behaves exactly the same as it did with 4.1.0. Could you take another look?

**Comment by milostosic** [comment]
Could you provide some additional information? I've tested this today and it worked fine.
Maybe it would help invoking it with added '.com' extension like this:
   
   mtuner**.com** -p wfsp.exe -c "/exe"

**Comment by djelinski** [comment]
I tested this more thoroughly and here goes:
> mtuner.com -p wfsp.exe -c "/exe"

Unrecognized argument: "\exe"
> mtuner.com -p wfsp.exe -c "-exe"

No arguments passed.
> mtuner.exe -p wfsp.exe -c "/exe"

Passed argument: "/exe". This one is good.
> mtuner.exe -p wfsp.exe -c "-exe"

No arguments passed.

And one more as an experiment:
> mtuner.exe -p wfsp.exe -c " -exe"

(Note space before -exe in command line, no space in output): Passed argument: "-exe".

Just in case I verified the previous release, and found that the behavior was just the same.

The issue can be easily reproduced here using the following command line:
> mtuner.com -p c:\windows\system32\cmd.exe -c "/?"

With mtuner.exe this displays cmd help. With mtuner.com it just starts cmd.

SHA1sum:
af9340dd60d33e46f15cf6c90d1750591b57fe8d *MTuner.exe
914d8e7a953cf8b853a049008445ac75c04bf239 *MTuner.com

**Comment by milostosic** [comment]
You must use .com for command line usage, not .exe directly.

You've started cmd with this command:
     mtuner.com -p c:\windows\system32\cmd.exe -c "/?"
Once you close cmd window, capture file will be saved at displayed location.
This is expected behavior. Attached are two images showing me running the same command and showing that the capture was, indeed, recorded.

<img width="317" alt="capture_1" src="https://user-images.githubusercontent.com/1654399/43315055-68850e16-91c7-11e8-9316-46766c6f3166.png">
<img width="396" alt="capture_2" src="https://user-images.githubusercontent.com/1654399/43315056-68b33a8e-91c7-11e8-9210-a047d39756c2.png">

**Comment by milostosic** [comment]
I've just uploaded a new release. Found and fixed a bug that was causing slashes in command line arguments passed to child  processes to be converted to back  slashes. I've got the expected result from our sample command line. Thanks for the info!

**Comment by djelinski** [comment]
Thank you, indeed looks much better now!
It is still not possible to pass parameters starting with -, but that's something I can live with now.

**Comment by milostosic** [comment]
No problem, but now I need to check the arguments starting with '-'  :)

**Comment by milostosic** [comment]
Do you have a specific command line that gave you trouble with '-' arguments? Have you used quotes around those? Thanks!

**Comment by djelinski** [comment]
I couldn't remember of any readily available Windows program that would accept parameters starting with -, so I got creative:
> mtuner -p mtuner -c -help

I expect to profile mtuner with -help parameter, but the above command line just displays help message without actually profiling anything.
> mtuner -p mtuner -c " -help"

(note space before -help) This one actually starts profiling. Also it crashes, but that's unrelated.
