### ISSUE TITLE
'Call stack tree' and 'stack trace' tabs are empty in 4.3.1

### ISSUE THREAD

**Issue by crolopez** [milostosic/MTuner#48]
Hi,

I have been testing the leak detection capabilities of MTuner to integrate it in the [Wazuh](https://github.com/wazuh) testing protocol and I saw that the `call stack tree` and `stack trace` tabs are empty in MTuner 4.3.1. 

![image](https://user-images.githubusercontent.com/20266121/64121659-c596cf80-cd9f-11e9-98a9-85d0d687709c.png)

![image](https://user-images.githubusercontent.com/20266121/64121642-badc3a80-cd9f-11e9-87bc-4859d16f54c0.png)

The test is running with the following code:

``` C
#include <windows.h>
#include <stdio.h>

int main(int argc, char** argv) {
  char * a = malloc(3333);
  char * b = malloc(1234); //  Unreferenced memory
  char * c = malloc(4444); //  Still referenced
  char * d = malloc(1385);
  char * e = malloc(2385);

  b = a;

  free(a);
  free(d);

  return 0;
}
```

However, after reading the issue https://github.com/milostosic/MTuner/issues/37, I tried 4.0.9 and everything worked as expected.

![image](https://user-images.githubusercontent.com/20266121/64121758-0b539800-cda0-11e9-8bce-2b12f2c787dd.png)

![image](https://user-images.githubusercontent.com/20266121/64121752-07c01100-cda0-11e9-8895-6ee0d31f631c.png)

On the other hand, I can't differentiate the leaks due to unreferenced memory from the leaks still referenced. Is there a way? 

Best regards,
Cristobal Lopez.

**Comment by JuantAldea** [comment]
I'm running into the same issue.

**Comment by milostosic** [comment]
Tracked down to FPO in x86 build.
