### ISSUE TITLE
Console is not shown

### ISSUE THREAD

**Issue by tim-lebedkov** [milostosic/MTuner#49]
Profiling a command line application on Windows does not show a console. MTuner 4.3.1

**Comment by tim-lebedkov** [comment]
this does not work either and seems to open another console:
"C:\Program Files\MTuner\MTuner.com" -p katPRINTPerfTests.exe -w %cd%

**Comment by RandomGuy252** [comment]
An option to show the console would be very helpful indeed.

**Comment by milostosic** [comment]
Fixed in v4.4.2
