### ISSUE TITLE
Support additional memory allocators

### ISSUE THREAD

**Issue by matbech** [milostosic/MTuner#5]
It would be nice if additional memory allocators are supported. For example:
CoTaskMemAlloc / CoTaskMemFree
SysAllocString / SysAllocFree
LocalAlloc / LocalFree

**Comment by milostosic** [comment]
This should be just a several additional hooks, I'll look into it.

**Comment by milostosic** [comment]
I just double checked and all of those are already tracked as all of them internally call RtlAllocateHeap.
