### ISSUE TITLE
Opening file hard crashes MTuner

### ISSUE THREAD

**Issue by keithsw1111** [milostosic/MTuner#50]
I ran my GCC Release compiled C++ code using MTuner but both when I terminated the process and when It try to open the .MTuner file it hard crashes. If you want to look at the MTuner file I have placed it here: https://www.dropbox.com/s/76nxu08r1efau3c/xSchedule.2019.11.15.18.51.36.59.MTuner.zip?dl=0

**Comment by milostosic** [comment]
Fixed in v4.3.2.
