### ISSUE TITLE
partially loaded

### ISSUE THREAD

**Issue by gjaegy** [milostosic/MTuner#54]
Hi, I've got some issue with the trace file being partially loaded...
It's a pretty big one (9.4 GB). Any idea how I could avoid that error ?
Thanks a lot !

**Comment by milostosic** [comment]
This can mean one of two things - there was an error somewhere during a capture and the file is corrupt from that point or, a much more likely scenario, profiled process was terminated before the capture was flushed out and you will only be missing a small number of memory operations towards the end of the profiled application lifetime. So basically, in 99.99% of the cases, you can just ignore this and treat it more as a warning/info than an error.

**Comment by gjaegy** [comment]
I assume I'm then in the 0.01% cases :) The report shows me numerous memory leaks, which are not correct, so I assume the last part of the capture (containing the "free" calls) are either missing, or not processed when MTuner is opening the capture (possible cause => not enough memory ?).

Any idea how I can find out what's causing my issue ? 

Really, we have a lot of allocation calls (since using a custom allocator which is very performant), I'm pretty sure that's causing the issue somehow. This only occurs when testing very heavy scenarios (like generating a scene in the editor).

**Comment by milostosic** [comment]
First question, are you using the latest release of MTuner? A race condition has been fixed that may cause something like this. If you're using an older one, please try again.
If not.. Any chance to provide more information? That file is rather large to send around, and I assume it may contain some information that you cannot share as well.. So lets first eliminate the first option please.

**Comment by gjaegy** [comment]
Yes, I actually updated to 3.4.5, that's the version used when this issue occured (but tested a memory-heavy scene generation process, what I had never done with earlier versions).

**Comment by milostosic** [comment]
Ok, thanks for confirming that. Any chance to get my hands on that capture so I can debug it locally?
Or.. any chance to do the same with some similar repro, in case this file is too large to upload somewhere or you have sensitive information inside?

**Comment by gjaegy** [comment]
Thanks for your help. I'll upload the file somewhere, I will let you know once done.

**Comment by milostosic** [comment]
Fixed in v4.3.8 - big thanks to @gjaegy
