### ISSUE TITLE
How to change the location of the .Mtuner?

### ISSUE THREAD

**Issue by whu-lyh** [milostosic/MTuner#57]
Under window10, the .MTuner is created in the location "C:\Users\xxx\AppData\Roaming\MTuner", but my c drive has no enough space to store the big .MTuner file, so anybody know how to change the location of .MTuner?
Thanks~ everyone

**Comment by milostosic** [comment]
It's a choice of path that guarantees write access, unlike working directory of an executable. I will not be changing this. If you do need something else you can compile MTuner and change relevant code in rmem library that uses CSIDL_APPDATA to get the path.
