### ISSUE TITLE
Allocation stack trace in timeline range

### ISSUE THREAD

**Issue by vlmillet** [milostosic/MTuner#59]
Hi, I post it here as I don't know where to put it elsewhere. 
I cannot find a way to see allocation calls happening during a specific time range of the timeline, is it possible ? If not, that could be really a big improvements to track leaks by just observing the timeline and spotting the relative source code when allocations seem to grow when they shouldn't.

**Comment by milostosic** [comment]
Please read documentation and, more specifically, section about filtering. This is one of the core features of MTuner.
