### ISSUE TITLE
Drag & drop of executables doesn't work (Windows 10)

### ISSUE THREAD

**Issue by aardappel** [milostosic/MTuner#6]
It show the "circle with line" mouse cursor anywhere over the Mtuner window.
There's also doesn't appear to be any other way to load an executable (in the menus).

**Comment by milostosic** [comment]
I had some issues with access rights and drag & drop, across pretty much everything I use on Windows. So if you could provide some additional info it would be very useful. 

Regarding loading executables, besides drag & drop, you can use project manager dialog to setup and run executables with arguments and workingi directories. There's more info in the docs.

**Comment by aardappel** [comment]
I tried running MTuner with "run as administrator", same problem. What additional info do you want?

Applications work best if you can find what you want without reading the docs :) It wasn't obvious to me that "manage projects" would be the way to load up an executable, especially when it's not in the File menu.

**Comment by milostosic** [comment]
I assume you're running MTuner 3.6.8? I just tried it on Windows 10 and it worked fine... 
Frankly, no idea what could cause this problem for you.

Point taken for the menus :)

**Comment by milostosic** [comment]
Just saw this thread: https://www.tenforums.com/general-support/6868-no-drag-drop-windows-explorer-other-oddities.html
Some people suggest that pressing ESC during dragging can resolve the problem.

**Comment by milostosic** [comment]
Found this explanation: https://stackoverflow.com/questions/37828617/drag-and-drop-not-working-if-application-lies-in-specific-directory
I can confirm it's consistent with what I'm seeing - a non-elevated app can't send events to elevated apps. Running MTuner from Visual Studio (elevated) doesn't receive any D&D events from explorer but running it non-elevated works just fine. I checked it all in Details/Elevated column in Task Manager.
Can you check if this is the case?

**Comment by Mistuke** [comment]
> Regarding loading executables, besides drag & drop, you can use project manager dialog to setup and run executables with arguments and workingi directories. There's more info in the docs.

Omg, I was scratching my head on how to do this http://mtuner.net/doc/ui_manageproj.html, maybe you should make this easier to discover :). Maybe a a drag and drop target that opens up a dialog for extra options before running?

**Comment by milostosic** [comment]
Drag & drop dialog for extra options - sounds good, I'll add it to TODO list, thanks!
Guess it's time to close this one
