### ISSUE TITLE
After adding a project, MTuner doesn't launch it anymore

### ISSUE THREAD

**Issue by srogatch** [milostosic/MTuner#60]
I was launching successfully an executable by means of entering its path and working directory in Projects manager window.
Once I decided to save these settings. However, after that nothing started to happen upon a click on "Run" button.
The environment is Windows 2016 64-bit. The executable is built with MSVS 2019.

UPDATE: Apparently this happens if MTuner is launched from a working directory that is not the directory where MTuner executables are located.

**Comment by milostosic** [comment]
Fixed in v4.4.6
