### ISSUE TITLE
Minimize window on Windows closes all widgets.

### ISSUE THREAD

**Issue by vanaur** [milostosic/MTuner#61]
Hello,
I'm sorry to disturb for so little, but I noticed a small bug with the use of MTuner's GUI on Windows (I haven't tested it on Linux), it's absolutely not a priority, but nevertheless somewhat annoying repeatedly:

By minimizing the program window, the widgets close (see image). All you have to do is reactivate them in the `View` menu, however, not having to do so would be nice.
![](https://user-images.githubusercontent.com/28791317/85174142-0a2f2100-b275-11ea-9d79-ff896c0216c8.PNG)

**Comment by milostosic** [comment]
ouch, that indeed is a silly bug that I somehow haven't noticed :/ 
will check it out soon

**Comment by milostosic** [comment]
Fixed in v4.4.6
