### ISSUE TITLE
Tooltip disappears after ~1 second even though the mouse is not moving

### ISSUE THREAD

**Issue by pierricgimmig** [milostosic/MTuner#62]
When hovering on the timeline, I would expect the tooltip to stay visible even when the mouse is not moving. A workaround is to click in the timeline window to lock the tooltip but I find that it's not ideal.

I'm using the released version 4.4.6.

**Comment by milostosic** [comment]
Added a tool tip timer in v4.4.7, Qt doesn't respond to passed time out value for tool tip.
