### ISSUE TITLE
Tooltip size varies in the timeline

### ISSUE THREAD

**Issue by pierricgimmig** [milostosic/MTuner#63]
In the timeline, the tooltip size is alternating between fitting the content and being way too big.

![image](https://user-images.githubusercontent.com/3687222/90079113-d217ed80-dcbb-11ea-9db8-8b8f795b44e2.png)

vs

![image](https://user-images.githubusercontent.com/3687222/90078991-7a798200-dcbb-11ea-8c77-ef34d3a33c70.png)

**Comment by pierricgimmig** [comment]
This is in the released 4.4.6 version.

**Comment by milostosic** [comment]
This turned out to be a Qt but, changed Qt version for v4.4.7.
