### ISSUE TITLE
When filtering, negative values for memory leaks appear on top of the list

### ISSUE THREAD

**Issue by pierricgimmig** [milostosic/MTuner#64]
![image](https://user-images.githubusercontent.com/3687222/90080016-608d6e80-dcbe-11ea-94fa-0767e64682d3.png)

Is a negative value a deallocation that doesn't have a corresponding alloc in the selected timeline? If so, should it be displayed at all?

Released version 4.4.6

**Comment by pierricgimmig** [comment]
Also, we can see in the screenshot that some "Count" values seem wrong.

**Comment by milostosic** [comment]
Could not reproduce with latest release, closing for now.
