### ISSUE TITLE
It's unclear what the blue and green graphs are in the timeline

### ISSUE THREAD

**Issue by pierricgimmig** [milostosic/MTuner#65]
It's difficult to figure out what the green and blue graphs correspond to at first glance. A colored hint in the tooltip would be cool, or a legend in the graph.

**Comment by milostosic** [comment]
Tool tip now shows values using corresponding colors in v4.4.7.

**Comment by BitBlit88** [comment]
I think the colors are switched in the tool tip. Live blocks text should be green and usage text should be blue.
