### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by maidamai0** [milostosic/MTuner#68]
I have some problems #67  using this tool so I want to build myself and do some debugging.
But I got some problems when building according to the [doc](https://github.com/milostosic/MTuner#build)

#### What I have done

* Install [genie](https://github.com/bkaradzic/GENie#download-stable)
* Clone [dependencies](https://github.com/milostosic/MTuner#dependencies)

#### Problems I got

* when run `genie` I got an error:

```powershell
❯❯❯ genie vs2019
c:/Users/{usr_name}/Documents/MTuner/genie/genie.lua:14: attempt to call a nil value (global 'setPlatforms')
stack traceback:
        c:/Users/{usr_name}/Documents/MTuner/genie/genie.lua:14: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:114: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'
❯❯❯ genie vs2015
c:/Users/{usr_name}/Documents/MTuner/genie/genie.lua:14: attempt to call a nil value (global 'setPlatforms')
stack traceback:
        c:/Users/{usr_name}/Documents/MTuner/genie/genie.lua:14: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:114: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:46: in function '_premake_main'
```

#### OS & Compiler

```powershell
❯❯❯ cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

I also tried to install [Lua](https://www.lua.org/) but I got many problems when installing [luafilesystem](https://keplerproject.github.io/luafilesystem/). 

Do these problems related to **Lua**?

**Comment by milostosic** [comment]
Clone everything, you'll end up with something like this:
![image](https://user-images.githubusercontent.com/1654399/94524328-0e4fdf00-0265-11eb-8c71-7c733142dda8.png)

Then do this:
![image](https://user-images.githubusercontent.com/1654399/94524413-26276300-0265-11eb-83c2-60d0033921d0.png)

Keep in mind you need Qt installed and environment variables to point to installation, like this:

QTDIR_VS2017_x64=c:\Qt\5.14.2\msvc2017_64

And yes, lua with luafilesystem is needed, just copy it from somewhere if you can't easily install.
