### ISSUE TITLE
Can not use from command line

### ISSUE THREAD

**Issue by hywei** [milostosic/MTuner#69]
I have tried to use MTuner from command line following the document: [https://milostosic.github.io/MTuner/command_line/](url).
However, the result is wrong.
1. The help command result:
![help](https://user-images.githubusercontent.com/388972/95831613-d4560100-0d6b-11eb-91a4-60226194c8f8.png)

2. No .mtuner file created with "-p"
![p](https://user-images.githubusercontent.com/388972/95831774-0d8e7100-0d6c-11eb-91e3-d9107ceba7f8.png)

3. Can't generate xml file
![xml](https://user-images.githubusercontent.com/388972/95832274-a7561e00-0d6c-11eb-845a-094025b99222.png)

**Comment by xplanes** [comment]
I've tried MTuner and it looks great! I'm having the same issue when trying to use it from the command line to analyse a capture file. Is there any update about this issue?

**Comment by Mico-Lee** [comment]
![image](https://user-images.githubusercontent.com/54880975/187131707-66e8a2a7-49d0-4cfc-9778-ae5997e5ba5a.png)
I also encountered this problem, no response after execution.

**Comment by milostosic** [comment]
@hywei rmem_sample_manual is not meant to be instrumented by MTuner as (as it's name implies) it is using manual instrumentation for allocation tracking.

Leaving this open as there are likely some bugs with command line usage.

**Comment by milostosic** [comment]
Fixed in v4.4.9
