### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [milostosic/MTuner#7]
Would you like to [wrap any pointer data members](https://github.com/milostosic/MTuner/blob/5b931a21d0401867ad1800789cc1aa552d37d09a/src/loader/binloader.cpp#L15 "Update candidate: BinLoader class") with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by milostosic** [comment]
No, I do not use or like "smart" pointers.
