### ISSUE TITLE
libdep.a (i.e. binutils under MSYS2) is either not designed to run on Microsoft Windows or it contains an error

### ISSUE THREAD

**Issue by phobos-dthorga** [milostosic/MTuner#70]
Hello!

In the process of attempting to use your amazing memory profiling application, I am greeted with the following error depicted at the screenshot [ 1 ] shown below.

[ 1 ] - https://imgur.com/a/MNi1e34

The library it references seems to be tied towards `binutils` within [MSYS2](https://www.msys2.org/) which we use for compiling our [Small World Deluxe](https://code.gekkofyre.io/amateur-radio/small-world-deluxe) project (i.e. the application under test) and we are not able to proceed any further from here, with MTuner immediately freezing after closing that dialog (which appears at least twice). We have to forcibly end the task.

I see that MSYS2 is referenced within the Issues database of this project (see: Issue #38), albeit sometime ago, so I'm not sure why support for it is no longer present? Unless perhaps something has changed in the meantime since then. Any and all help would be sincerely appreciated, thank you, as I'd very much like to use MTuner as part of the testing and qualifying process for Small World Deluxe.

--
Regards,
Phobos D'thorga

**Comment by milostosic** [comment]
Can you attach the screenshot here? I can't seem to open it.

**Comment by phobos-dthorga** [comment]
Hello @milostosic,

Apologies, I didn't know you could attach screenshots to GitHub! You may view it below :)

![MTuner_77CuAfoWpR](https://user-images.githubusercontent.com/10932524/107326107-02bbd100-6aff-11eb-86ce-3be9bd534dd3.png)

--
Regards,
Phobos D'thorga

**Comment by prgwiz** [comment]
Getting the same error when building open source package harbour.

**Comment by MarcosLeonardoMendezGerencir** [comment]
the same error

**Comment by milostosic** [comment]
Since quite a few people seem to have this problem - does anyone have a simple way to reproduce it? Would save me a lot of time that I'm quite short on anyway

**Comment by phobos-dthorga** [comment]
I have no clue how you'd reproduce this. Hopefully, someone knows a way.

**Comment by MarcosLeonardoMendezGerencir** [comment]
https://github.com/MarcosLeonardoMendezGerencir/hb-raylib
This library gives the error

**Comment by milostosic** [comment]
It's clearly toolchain related and, by extension, build process used. So sending me a link to code doesn't help - if you can share your build process/scripts that I can follow to locally reproduce a problem then it should be reasonably fast for me to find the problem.

**Comment by MarcosLeonardoMendezGerencir** [comment]
Does it have something to do with the executables being dependent on the libwinpthread-1.dll?

**Comment by prgwiz** [comment]
Looks like it has something to do with the ar command.
![Capture](https://user-images.githubusercontent.com/6751439/109981324-cc710c00-7cce-11eb-8616-356f542406c1.PNG)

**Comment by prgwiz** [comment]
https://github.com/msys2/MINGW-packages/issues/7890
