### ISSUE TITLE
I couldn't find qtpresets5.lua everywhere.

### ISSUE THREAD

**Issue by pengguanjun** [milostosic/MTuner#72]
I try to build MTuner, but I failed.

My effort is following as:

```
cd MTuner/genie
./genie.exe --gcc=mingw-gcc gmake
cd ../../.build/windows/mingw-gcc/MTuner/projects/
D:/installPath/QT5.12.8/Tools/mingw730_32/bin/mingw32-make.exe
```

![image](https://user-images.githubusercontent.com/29192658/123230527-eb0f4300-d509-11eb-9807-35f07e601bf2.png)

Error!
> $ ./run.sh
> Set MINGW environment variable.
> ERROR: The QTDIR_GMAKE_x86 environment variable must be set to the Qt root directory to use qtpresets5.lua
> mingw32-make: *** No targets specified and no makefile found.  Stop.

I try some path configuration to QTDIR_GMAKE_x86, such as:
![image](https://user-images.githubusercontent.com/29192658/123230135-80f69e00-d509-11eb-9649-2cd61af37326.png)
But,those all don't work.

And  I couldn't find qtpresets5.lua everywhere in local env and in the Internet.

Could you help me?

**Comment by milostosic** [comment]
Qt version support has been moved to 6 and above. You'll find qtpresets6.lua file now.

**Comment by helloellite** [comment]
A awe project but also with the most detailless build documentation I've seen...

**Comment by milostosic** [comment]
Qt 6 should be used, you can find qtpresets6.lua here: https://github.com/milostosic/build/blob/master/qtpresets6.lua
You could back port it to Qt 5 with a minor edit.

I won't have access to a real dev computer for a few more weeks so can't check in detail now what's going on.
