### ISSUE TITLE
Request for supporting following forked/child processes, or attaching to process

### ISSUE THREAD

**Issue by aravind2612krishna** [milostosic/MTuner#73]
Thank you for writing this tool.
In some use cases, the actual executable to be profiled is forked by another process.
In that case, unless we can attach to a process id or follow child processes, it is impossible to profile.
Please consider adding support for this.

**Comment by milostosic** [comment]
What's the use case for this?

**Comment by aravind2612krishna** [comment]
Like I said, the actual executable to be profiled is forked by another process. In that case I'm not sure I can profile it without attaching to process id, or MTuner following each child process and creating a separate MTuner file for each.

**Comment by milostosic** [comment]
Again, it what scenario does this happen? Anyway, I don't see this as something that is worth my time but feel free to contribute - it's open source for a reason.
