### ISSUE TITLE
Support on next gen consoles

### ISSUE THREAD

**Issue by GenderMurasaki** [milostosic/MTuner#76]
Is there any plan to add support for Prospero and Scarlett?
It should be straightforward due to similarities with the previous generation.

**Comment by milostosic** [comment]
While I agree this should be very easy, unfortunately I don't have access to those devkits so there's no way for me to develop/test it. Open for contributions though, if you're (or someone else is) interested to work on it I'd be glad to assist you.

**Comment by GenderMurasaki** [comment]
I understand, thank you for the quick answer.

For the previous generation, I wanted to ask about the state of XboxOne. It seems that rmem supports it, but the toolchain is ignored by MTuner.exe, so it is not possible to load symbols for it.

Am I missing something, or is it not supported today?

**Comment by milostosic** [comment]
It's not fully supported out of the box, but I've had reports of people getting it to work with some minor tweaks.
