### ISSUE TITLE
Unable to build in macOS

### ISSUE THREAD

**Issue by PabloPicose** [milostosic/MTuner#77]
Hi! Im unable to compile from source using the "build" genie system on macOS, I follow your tutorial .
I use this command to generate the solution
genie --gcc=osx gmake
I tested passin xcode11 as argument and I get the same result.
`qtprebuild.lua:180: error: MOC Failed to generate /Users/******/Documents/repo/rqt/src/../.qt/qt_moc/rqt_widget_categorized_list_moc.cpp
lua "/Users/******/Documents/repo/build/qtprebuild.lua" -moc "/Users/******/Documents/repo/rqt/inc/rqt_widget_assert.h" "/Users/pablopicoserrano/Qt/6.3.0/macos/" "rqt" "../../inc/rqt_widget_assert.h"
`
`../../../../../rqt/src/rqt_pch.h:17:10: fatal error: 'QtCore/QByteArray' file not found`

Maybe Im missing something?

**Comment by milostosic** [comment]
I've built is on OSX long time ago, you can refer to .travis.yml. But MTuner does not support OSX now and would require work- I have no plans to do this but I welcome contrbutions.
