### ISSUE TITLE
Qt License Information is wrong

### ISSUE THREAD

**Issue by nezticle** [milostosic/MTuner#8]
On the Open source license page it states:

> Qt (LGPL) 
> 
> Qt - Cross-platform application and UI framework. 
> 
> https://qt-project.org/ 
> 
> Qt is available under the LGPL (version 2.1).
> The Qt Toolkit is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies) and other contributors.

The current release of MTuner 3.6.8 links against Qt 5.7.0 which does not actually have an LGPL 2.1 license for the Qt Modules being used[core, gui, network, widgets].  (Qt 5.6.x was the last to offer this version of LGPL).  Current licenses available for Qt 5.7 and up are here:
https://www.qt.io/licensing-comparison/

Also current Copyright company is: The Qt Company Ltd. instead of Digia Plc (you can see this in the current license headers).

**Comment by nezticle** [comment]
Here is maybe a better link:
https://www.qt.io/faq/#_Toc_1_2
Solution is to change this to use Qt under the LGPLv3 license or GPLv2 or GPLv3 if you are going to use 5.7 and higher.

**Comment by milostosic** [comment]
Thanks for pointing this out, I updated the info in the repository.
New binary releases will pick this up.
