### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by lavyadrian** [milostosic/MTuner#84]
Hey! Does this work on linux? If so can the README be updated to include steps on how to do it? Thanks.

**Comment by milostosic** [comment]
Hey! No, it doesn't work and would need some extra work but I rarely touch Linux so can't commit to it. I'd be happy to get a pull request. Someone would need to deal with injecting processes (LD_PRELOAD or something) and implement a few spots that are platform specific but most code should be ok - it does compile.

**Comment by milianw** [comment]
You can take inspiration from https://invent.kde.org/sdk/heaptrack or https://github.com/koute/bytehound
