### ISSUE TITLE
Mtuner memory usage different with system

### ISSUE THREAD

**Issue by CgGraphic** [milostosic/MTuner#87]
I intend to use Mtuner to profile my application so that I can find the memory usage of the different modules (dll).

But I have found that Mtuner gives merely 512MB usage, while my application use over 10GB .
![image](https://user-images.githubusercontent.com/8565304/220050108-351c2d3f-742e-4312-80df-e994497aa64a.png)

Is there something wrong?

**Comment by milostosic** [comment]
It depends what you mean by 'my application use over 10GB'. If you allocate 10GB and MTuner is not catching that, I'm curious to hear more.

**Comment by CgGraphic** [comment]
It's a game engine, that handles tens of gigabytes of assets.  So definitely more than 512MB

**Comment by milostosic** [comment]
How are you performing the capture?

**Comment by CgGraphic** [comment]
![image](https://user-images.githubusercontent.com/8565304/220122535-b9b7cabb-bcd3-420d-83a9-52f8cdbfdbe4.png)

**Comment by CgGraphic** [comment]
OK, I will look into the MTuner SDK code. Thank you
