### ISSUE TITLE
Timeline selection is not filtering views

### ISSUE THREAD

**Issue by rsmz** [milostosic/MTuner#89]
According to the documentation, it sounds like highlighting a range or clicking in the Memory timeline plot should filter data in the central views, such as the Operations tab or Call Stack Tree tab, but I do not see it doing anything. Maybe there is a button I don't see that I need to press to update the views?

**Comment by milostosic** [comment]
You may want to try and read the documentation before opening issues. Have you tried toggling filtering *on*?
