### ISSUE TITLE
How to use on PS4

### ISSUE THREAD

**Issue by Vultra** [milostosic/MTuner#9]
Hello, is there any documentation on how to use this with a PS4 Console ?

**Comment by milostosic** [comment]
PS4 toolchain must be configured, documentation on that is [here](http://mtuner.net/doc/ui_gcctoolchains.html).

You would also need to integrate [rmem](https://github.com/milostosic/rmem) into your code,  and save capture files on the devkit, some documentation about that is [here](http://mtuner.net/doc/sdk.html).
